files: speakerbox
repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.216
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
